### ISSUE TITLE
show group captures in table 3?

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#108]
@ChristopherTracey  - I notice you only show results for reaches in Table 3. I've dropped the EO and poly columns but have kept a column for groups. If you are still validating by groups, wouldn't you still want to have a groups column in this table?

https://github.com/HeritageNetwork/Regional_SDM/blob/83bffe3f92e3a2edad51909d9acc1102716c23e0/MetadataEval_knitr.rnw#L317

**Comment by ChristopherTracey** [comment]
Yes, it would be a good idea. I'm guessing this is a legacy thing from the aquatic conversion. I'll get on it.

**Comment by ChristopherTracey** [comment]
**Ooof** --- This took some time to fix.  Initially, when we developed the aquatic scripts, we weren't using a grouping variable, so we commented out all the lines in 4b that used `eo_id_st`. Then modify the code to use the new presence file scheme (#14).

@memoore - we need to make some modifications to the grouping tool to make the new input file.

**Comment by ChristopherTracey** [comment]
Double ooof...  I just noticed that the number of percentage of the groups is greater than 100%.  Will fix tomorrow.

**Comment by tghoward** [comment]
but you should have been tracking groups somehow?

**Comment by ChristopherTracey** [comment]
I believe we were.  We had two main issues that were causing issues.
The first was that we didn't have a line in script 3 to store the total number of groups as we did in Terrestrial: 
https://github.com/ChristopherTracey/Regional_SDM/blob/1de44ce97fd09e141edd605043efbd583b6feb27/3_createModel.R#L212
Secondly, in 4b, the creation of the `allThresh` dataframe was duplicating the number of reaches, and not groups due to a bad index.

@tghoward, you may want to take a look at the aquatic branch to confirm its using groups correctly.

**Comment by tghoward** [comment]
> Secondly, in 4b, the creation of the `allThresh` dataframe was duplicating the number of reaches, and not groups due to a bad index.

hmm. yes, we probably should be calling those indices by name, not number, to eliminate potential errors in building the `allThresh` data frame.

**Comment by tghoward** [comment]
> hmm. yes, we probably should be calling those indices by name, not number, to eliminate potential errors in building the `allThresh` data frame.

fixed indexing in #146
