### ISSUE TITLE
AquaGroup: sampsize larger than class

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#204]
Issue with the wood turtle
> Error in randomForest.default(x, y, mtry = mtryStart, ntree = ntreeTry,  : 
>   sampsize can not be larger than class frequency

**Comment by tghoward** [comment]
aha. Found the culprit. At least part of the culprit.   Background reaches get knocked down to 3000 records here:

https://github.com/HeritageNetwork/Regional_SDM/blob/ef8b5dc98c59247c073a29ebfabda0723c236f50/1_pointsInPolys_cleanBkgPts.R#L170-L172

That's why there aren't enough background reaches with the spp with huge numbers of presence records.   

seems like these numbers could be reduced in script 3 if needed.
