### ISSUE TITLE
Add additional thresholds into aquatic metadata

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#52]
Minimum reach group, etc

**Comment by ChristopherTracey** [comment]
MTP by Reach Group is now included.  @dnbucklin are there other ones we wanted to add?

**Comment by dnbucklin** [comment]
I think I already added all the ones we had used previously in 58877f8. 

MRV (Minimum Reach Value) is probably the only "new" one - which is unique because it's calculated from the final model predictions, not OOB values like the other thresholds. We found this useful in a lot of cases where all the other thresholds were very low.

**Comment by dnbucklin** [comment]
Oh, I think I read this wrong at first. I'd probably leave MRV out of the metadata anyways since it's calculated on different data, so it seems fine to leave it out of the `lkpThresholdTypes` table.

**Comment by ChristopherTracey** [comment]
Ok.

**Comment by ChristopherTracey** [comment]
Closing for now, as I think we're good.
