### ISSUE TITLE
why huc12 in background on terrestrial branch?

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#62]
I'm confused about background points generation and attribution on the terrestrial side.  Do we need Huc12 attribution? Do we need it in an sqlite db? 

https://github.com/HeritageNetwork/Regional_SDM/blob/1630bc1437d4ab19230a77eda84888185e0a9230/preprocessing/preproc_makeBackgroundPoints.R#L14

**Comment by dnbucklin** [comment]
This was discussed [here](https://github.com/HeritageNetwork/Regional_SDM/issues/27#issuecomment-436308623). 

The thinking was we could use the HUC information to query background points (without having to do anything spatially) from the big table storing all background points, since the ranges are based on HUCs.

I think this was before I knew about querying a shapefile using `st_read`, so I assumed we'd want an SQLITE database. But I think we could choose one the other now; we don't need both.

**Comment by ChristopherTracey** [comment]
Not yet, but I'm building a WKT version at the moment for the model extent part of the metadata. I can put a shapefile version up as well.

**Comment by tghoward** [comment]
Ok. Yes, `preproc_makeBackgroundPoints.r` uses a shapefile currently. Thanks.

**Comment by tghoward** [comment]
@ChristopherTracey , ok thanks. I've unzipped and placed it here. `N:\rangestuff\HUC_ref\huc12_fromChris`

I'm actually a little worried about provenance. E.g. Amy's HUC12 might be different than yours. So I'm trying to keep track.

**Comment by ChristopherTracey** [comment]
It's at N:\chris\huc12.7z, move to wherever you need it.

**Comment by ChristopherTracey** [comment]
Sorry about the misplace. My HUC 12 came from Watershed boundary dataset that's part of the NHD. It's as official as it can get.

**Comment by tghoward** [comment]
Yes, but they have different versions/years, right?

**Comment by ChristopherTracey** [comment]
I think so. @akconley where did you HUC layer come from?

**Comment by akconley** [comment]
From the  USGS National Watershed Boundary Dataset (WBD) 20140924 National
FileGDB 10.1

**Comment by ChristopherTracey** [comment]
From what I can tell, I think I'm using a 2018 version. It's not clearly labeled in the NHD Seamless download. They got to be close right?  Watershed's don't change much...

**Comment by akconley** [comment]
Tim brought it up because at some point between our Great Lakes project in
2015 and our statewide tribs project in 2017 the HUC12s all around the
shore of lake Onatario were changed so that the lakeshore was one
continuous huc12. It meant we had to redo the whole basin. I don’t know if
the HUC10changed. I’ll look when I’m back in tomorrow. Another option -
since modeling won’t start right now is to compare the 2018 HUC10 with my
master and if they aren’t the same redo the ranges

**Comment by ChristopherTracey** [comment]
Ok. Sounds good.  We should probably try to use the mode modern HUC layer as we can.

**Comment by ChristopherTracey** [comment]
Now with color and actual words:
![image](https://user-images.githubusercontent.com/8216371/50233807-39b05500-0382-11e9-984f-0dcc005958b0.png)

**Comment by akconley** [comment]
Hey Chris-
When you grabbed your HUC12s, did you get the whole WBD set (HUCs 2-12)? I
ask because when I went to grab the most current version from here (
https://www.usgs.gov/core-science-systems/ngp/national-hydrography/access-national-hydrography-products)
I saw this note that :

   - "WBD dataset by Entire Nation are refreshed monthly"

So theoretically  it is possible there have been changes since you grabbed
the WBD. If you have a HUC10 feature class from your same version, can you
put it on MobiPrep? Otherwise I shall download whatever they are offering
now.
~amy

**Comment by ChristopherTracey** [comment]
The WBD snapshot only appears to be the  HUC12 layer, but there are columns for HUC10 and other levels in the attribute table, so one could dissolve them. 

The gdb is here on MoBIprep: N:\NationalWBDSnapshot.gdb.7z
