### ISSUE TITLE
folder/file structure

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#8]
@ChristopherTracey @dnbucklin Since the PR where we started talking about this is closed (https://github.com/HeritageNetwork/Regional_SDM/pull/4), opening up the discussion again here. 

If I'm following correctly, the excellent wrapper system in aquatic (and master) creates folders within a folder named by species code (for example). It also puts, and references, a full set of the repository (the scripts) in there.  (species/sppcode/inputs/scripts/Regional_SDM_date). 

Since the wrapper will  build this file structure for you, I find myself running the wrapper from one copy of the repository, but then somewhere along the line (right away?) it drops into and uses the scripts from the other repository. 

I think I understand the reasoning for wanting to save a set of *the* scripts that were used in that particular run, but it also seems a little funny to not be using the scripts that you have loaded in RStudio!

Perhaps it might make more sense to save the version (commit #?) of the repository but not the entire repository? Can one of you discuss the reasoning here? 

Thanks,
Tim

**Comment by dnbucklin** [comment]
@tghoward The reasoning was really to automate pulling the most up to date scripts, and also to have the actual scripts saved that were used in a model run. It really wasn't necessary for it to be as a full copy of the git repository, but this feature did have its benefits when I needed to re-visit certain models (I just had to pull the updates). This also allows you to keep your "master" scripts (in your RStudio project) separate from the species' scripts (or vice versa if you do need to make species-specific changes).

I did recently put together some instructions on how to proceed in different situations [here](https://github.com/HeritageNetwork/Regional_SDM/blob/aquatic/README.md#testingediting-scripts). In general, during testing I would always skip the `get_scripts.R` step and just set `loc_scripts` to be my main working `Regional_SDM` git repository path (the scripts loaded in RStudio),

Admittedly this isn't a workflow to use when you're actively developing the scripts and want to test new changes, and the wrapper `user_run_SDM.r` still could be made easier to use. And maybe for this project's "final" models it would make more sense to just save the latest commit hash, or perhaps instead of the full git repo, a true script archive (e.g. saving the "numbered" scripts after they are used in the model run).

**Comment by dnbucklin** [comment]
Hmm, `exists()` can be dangerous in my experience...Would you like to do this in order to test one script a time? I think this can already be accomplished fairly simply already with `run_SDM` as is, by specifying `begin_step` and `prompt = TRUE`.

I'm actually just now about to pull request the file/`run_SDM` structure changes as I made for `aquatic` into `master` (e.g., the terrestrial version). Maybe as we're working through that we can decide how best to proceed?

**Comment by tghoward** [comment]
Ok, why don't you pull in those changes to master. I'm in the middle of moving script 1 over to sf and can merge that stuff in after yours. 

> I think this can already be accomplished fairly simply already with `run_SDM` as is, by specifying `begin_step` and `prompt = TRUE`.

I'll give this a shot, but in refactoring, I'd even want more ability to go through the script.

**Comment by tghoward** [comment]
@dnbucklin yes, I have a very small test set (about six polys and a few point observations). I have not clipped rasters to the area yet (not there yet), but I can do that and share, probably tomorrow sometime. 

I want this to be pretty straightfoward for anyone on the tech team to be able to build their own test data set and test the scripts. 

also, using here(), it looks to me like we can remove a number of the arguments in the runSDM call?

**Comment by dnbucklin** [comment]
If you mean in `user_run_SDM.r` yes I think that would make a lot of sense, for `here` usage, especially if they can help make it more generic. I made an addition in .gitignore where you can create your 'customized' version of the file in the repo with the name pattern `user_run_SDM_[name].r`, which git will ignore.

For testing- in the last PR I set the script 4_ to crop the raster stack to the presence file automatically; this is just for testing and should be removed when a full extent prediction is needed. But it allowed me to run a "full" model test in ~5 minutes.

**Comment by dnbucklin** [comment]
I'll volunteer to handle these file structure things. Need to figure out `here` a bit more but it seems pretty straightforward.

**Comment by tghoward** [comment]
Ok on your offer to handle file structure. I think inside `_data` you need `databases`, `other_spatial`, and then the `species` folder in which the model run folders are generated and nested. There also needs to be a folder for the original inputs (polys and points) from which derivatives get copied to the model run folders. This might be `_data/inputs`. 

Again, I think there's a better solution to making a copy of the repository and running scripts that are not in the repository you are using. Let's avoid continuing down that path.
